/**
 * @name tools/builtin-tool-modules
 * @description Built-in SAP MCP tool module catalog.
 *
 * New first-party tool families should be added here as `createToolModule`
 * entries. Third-party/plugin integrations can reuse the same module contract
 * and pass additional modules to `registerToolModules`.
 *
 * @module tools/builtin-tool-modules
 */

import { sapNetworkStatsTool } from './sap-network-stats.tool.js';
import { registerAgentStartTool } from './agent-start-tool.js';
import { registerAdrenaTools } from './adrena-tools.js';
import { registerChatTools } from './chat-tools.js';
import { registerClientSdkTools } from './client-sdk-tools.js';
import { registerEstimateToolCost } from './estimate-tool-cost.js';
import { registerHostedPrepaidTools, registerX402PaidCallTool } from './x402-paid-call-tool.js';
import { registerMagicBlockTools } from './magicblock-tools.js';
import { registerMemoryTools } from './memory-tools.js';
import { registerPerpTools } from './perp-tools.js';
import { registerPremiumTools } from './premium-tools.js';
import { registerProfileTools } from './profile-tools.js';
import { registerQuickContextTool } from './quick-context-tool.js';
import { registerSapSdkTools } from './sap-sdk-tools.js';
import { registerSapSnsTools } from './sap-sns-tools.js';
import { registerSkillsTools } from './skills-tools.js';
import { registerTransactionTools } from './transaction-tools.js';
import { registerFearGreedTool } from '@oobe-protocol-labs/sap-mcp-perps/market-intelligence';
import { registerPortfolioRiskTool, registerRiskCheckTool } from '@oobe-protocol-labs/sap-mcp-perps/risk-engine';
import { registerSignalScoreTool } from '@oobe-protocol-labs/sap-mcp-perps/signal-engine';
import { createToolModule, selectToolModulesForContext, type ToolModuleDefinition } from './module-registry.js';
import type { SapMcpContext } from '@oobe-protocol-labs/sap-mcp-core/types';

export const BUILTIN_TOOL_MODULES: readonly ToolModuleDefinition[] = [
  createToolModule({
    id: 'payments-bridge-only',
    title: 'Payments Bridge Only',
    description: 'Local x402/pay.sh bridge helper surface for paid hosted MCP calls.',
    category: 'payments',
    order: 10,
    mode: 'payments-bridge-only',
    expectedTools: [
      'sap_payments_profile_current',
      'sap_payments_wallet_guard',
      'sap_payments_readiness',
      'sap_payments_process_status',
      'sap_payments_call_paid_tool',
      'sap_x402_paid_call',
      'sap_payments_call_external_x402',
      'sap_payments_register_agent',
      'sap_payments_update_agent',
      'sap_payments_finalize_transaction',
      'sap_payments_prepare_challenge',
      'sap_payments_sign_challenge',
      'sap_payments_verify_receipt',
      'sap_payments_prepaid_balance',
      'sap_payments_start_prepaid',
    ],
    register: registerX402PaidCallTool,
  }),
  createToolModule({
    id: 'sap-sdk',
    title: 'SAP SDK',
    description: 'Synapse Agent Protocol identity, registry, reputation, settlement, proof, and memory tools.',
    category: 'sap-protocol',
    order: 100,
    expectedTools: [
      'sap_register_agent',
      'sap_get_agent',
      'sap_update_agent',
    ],
    register: registerSapSdkTools,
  }),
  createToolModule({
    id: 'sap-sns',
    title: 'SAP SNS',
    description: 'SNS domain lookup, records, and SAP agent identity integration tools.',
    category: 'sap-protocol',
    order: 110,
    expectedTools: [
      'sap_sns_check_domain',
      'sap_sns_batch_check_domains',
      'sap_sns_resolve_domain',
      'sap_sns_validate_records',
      'sap_sns_get_domain_pda',
      'sap_sns_get_record_pda',
      'sap_sns_register_agent_domain',
      'sap_sns_get_domain_records',
      'sap_sns_get_record',
      'sap_sns_resolve_wallet',
      'sap_sns_check_ownership',
      'sap_sns_build_manage_record_transaction',
      'sap_sns_build_set_primary_domain_transaction',
    ],
    register: registerSapSnsTools,
  }),
  createToolModule({
    id: 'sap-network-stats',
    title: 'SAP Network Stats',
    description: 'Network-level SAP discovery and global registry statistics.',
    category: 'sap-protocol',
    order: 120,
    expectedTools: ['sap_network_stats'],
    register: sapNetworkStatsTool,
  }),
  createToolModule({
    id: 'client-sdk',
    title: 'Synapse Client SDK',
    description: 'AgentKit protocol tools and compatibility wrappers from the Synapse Client SDK.',
    category: 'integration',
    order: 130,
    expectedTools: ['sol_get_balance'],
    register: registerClientSdkTools,
  }),
  createToolModule({
    id: 'transaction',
    title: 'Transaction Tools',
    description: 'Decode, preview, sign, submit, and finalize Solana transactions.',
    category: 'solana',
    order: 140,
    expectedTools: [
      'sap_decode_transaction',
      'sap_preview_transaction',
      'sap_sign_transaction',
      'sap_submit_signed_transaction',
      'sap_build_sol_transfer',
      'sap_build_spl_transfer',
    ],
    register: registerTransactionTools,
  }),
  createToolModule({
    id: 'chat',
    title: 'Signed Agent Chat',
    description: 'Signed group room manifests, messages, history, and ciphertext transport tools.',
    category: 'sap-protocol',
    order: 150,
    expectedTools: [
      'sap_chat_derive_room',
      'sap_chat_start_room',
      'sap_chat_send_message',
      'sap_chat_publish_manifest',
      'sap_chat_read_latest',
      'sap_chat_read_all',
      'sap_chat_status',
      'sap_chat_seal_room',
    ],
    register: registerChatTools,
  }),
  createToolModule({
    id: 'x402-local-helper',
    title: 'Local x402 Helper',
    description: 'User-controlled local signer helper for paid hosted MCP calls.',
    category: 'payments',
    order: 160,
    expectedTools: [
      'sap_payments_register_agent',
      'sap_payments_update_agent',
      'sap_payments_call_external_x402',
      'sap_payments_finalize_transaction',
      'sap_payments_profile_current',
      'sap_payments_wallet_guard',
      'sap_payments_readiness',
      'sap_payments_process_status',
      'sap_payments_call_paid_tool',
      'sap_x402_paid_call',
      'sap_payments_prepare_challenge',
      'sap_payments_sign_challenge',
      'sap_payments_verify_receipt',
      'sap_payments_prepaid_balance',
      'sap_payments_start_prepaid',
    ],
    when: (context) => context.config.mode !== 'hosted-api' || Boolean(context.config.walletPath),
    register: registerX402PaidCallTool,
  }),
  createToolModule({
    id: 'hosted-prepaid',
    title: 'Hosted Prepaid Credits',
    description: 'Hosted prepaid balance and funding tools for non-custodial remote MCP deployments.',
    category: 'payments',
    order: 161,
    expectedTools: ['sap_payments_fund_prepaid', 'sap_payments_prepaid_balance'],
    when: (context) => context.config.mode === 'hosted-api' && !context.config.walletPath,
    register: (server, context) => registerHostedPrepaidTools(server, context),
  }),
  createToolModule({
    id: 'profile',
    title: 'Profile Tools',
    description: 'Profile inspection and runtime reload tools with redacted signer metadata.',
    category: 'profile',
    order: 170,
    expectedTools: [
      'sap_profile_current',
      'sap_profile_list',
      'sap_profile_public_key',
      'sap_profile_switch',
    ],
    register: registerProfileTools,
  }),
  createToolModule({
    id: 'agent-start',
    title: 'Agent Start',
    description: 'Concise bootstrap context for agent runtimes after tools/list.',
    category: 'agent-runtime',
    order: 180,
    expectedTools: [
      'sap_agent_start',
      'sap_agent_runtime_status',
      'sap_prepare_action',
      'sap_agent_standard_context',
      'sap_prepare_mandate',
      'sap_pricing_catalog',
      'sap_agent_next_action',
    ],
    register: registerAgentStartTool,
  }),
  createToolModule({
    id: 'estimate-cost',
    title: 'Estimate Tool Cost',
    description: 'Pre-call cost estimator for x402/pay.sh spending plans.',
    category: 'payments',
    order: 190,
    expectedTools: ['sap_estimate_tool_cost'],
    register: registerEstimateToolCost,
  }),
  createToolModule({
    id: 'quick-context',
    title: 'Quick Context',
    description: 'Single-call runtime, pricing, premium, skills, and tool discovery context.',
    category: 'agent-runtime',
    order: 200,
    expectedTools: ['sap_quick_context'],
    register: registerQuickContextTool,
  }),
  createToolModule({
    id: 'premium',
    title: 'Premium Runtime',
    description: 'Premium plugin catalogs, stream/webhook contracts, and session planning tools.',
    category: 'premium',
    order: 210,
    expectedTools: [
      'sap_premium_plugin_catalog',
      'sap_stream_catalog',
      'sap_webhook_catalog',
      'sap_premium_validate_plugin_manifest',
      'sap_premium_plugin_template',
      'sap_premium_session_start',
      'sap_premium_session_status',
      'sap_premium_activate_session',
      'sap_premium_close_session',
      'sap_premium_webhook_register',
      'sap_premium_webhook_unregister',
      'sap_premium_webhook_status',
      'sap_premium_webhook_relay',
      'sap_premium_webhook_relay_status',
      'sap_premium_metrics',
      'sap_premium_stream_poll',
      'sap_premium_stream_flush',
    ],
    register: registerPremiumTools,
  }),
  createToolModule({
    id: 'perps',
    title: 'Perps Analytics',
    description: 'Perpetual trading analytics, market data, and chart analysis tools.',
    category: 'perps',
    order: 220,
    expectedTools: ['sap_perp_markets'],
    register: registerPerpTools,
  }),
  createToolModule({
    id: 'adrena',
    title: 'Adrena Protocol',
    description: 'Adrena trading, SL/TP, limit order, commodity, liquidity, staking, and data API tools.',
    category: 'perps',
    order: 230,
    expectedTools: [
      'sap_adrena_get_positions',
      'sap_adrena_get_pool_info',
      'sap_adrena_get_custody_info',
      'sap_adrena_get_trader_info',
      'sap_adrena_get_trader_leaderboard',
      'sap_adrena_get_mutagen',
      'sap_adrena_get_mutagen_leaderboard',
      'sap_adrena_get_prices',
      'sap_adrena_get_trading_prices',
      'sap_adrena_get_position_status',
      'sap_adrena_get_markets',
      'sap_market_snapshot',
      'sap_adrena_build_add_liquidity',
      'sap_adrena_build_remove_liquidity',
      'sap_adrena_build_swap',
      'sap_adrena_build_add_limit_order',
      'sap_adrena_build_cancel_limit_order',
      'sap_adrena_build_open_commodity_long',
      'sap_adrena_build_open_commodity_short',
      'sap_adrena_build_close_commodity_long',
      'sap_adrena_build_close_commodity_short',
      'sap_adrena_build_init_user_staking',
      'sap_adrena_build_add_liquid_stake',
      'sap_adrena_build_remove_liquid_stake',
      'sap_adrena_build_add_locked_stake',
      'sap_adrena_build_claim_stakes',
      'sap_adrena_build_open_long',
      'sap_adrena_build_open_short',
      'sap_adrena_build_close_long',
      'sap_adrena_build_close_short',
      'sap_adrena_build_set_stop_loss',
      'sap_adrena_build_set_take_profit',
      'sap_adrena_build_cancel_stop_loss',
      'sap_adrena_build_cancel_take_profit',
      'sap_adrena_simulate_position',
      'sap_adrena_build_position_package',
      'sap_adrena_trade_intent',
      'sap_adrena_build_trailing_stop',
      'sap_adrena_build_modify_position',
    ],
    register: registerAdrenaTools,
  }),
  createToolModule({
    id: 'perps-risk',
    title: 'Perps Risk Engine',
    description: 'Perps risk checks and portfolio-level risk evaluation tools.',
    category: 'perps',
    order: 240,
    expectedTools: ['sap_perp_risk_check'],
    register: (server, context) => {
      registerRiskCheckTool(server, context);
      registerPortfolioRiskTool(server, context);
    },
  }),
  createToolModule({
    id: 'perps-signals',
    title: 'Perps Signal Engine',
    description: 'Signal scoring and market intelligence tools.',
    category: 'perps',
    order: 250,
    expectedTools: ['sap_perp_signal_score'],
    register: (server, context) => {
      registerSignalScoreTool(server, context);
      registerFearGreedTool(server, context);
    },
  }),
  createToolModule({
    id: 'skills',
    title: 'Agent Skills',
    description: 'Bundled SAP MCP skill listing, bundling, install, upgrade, and repair tools.',
    category: 'skills',
    order: 260,
    expectedTools: [
      'sap_skills_list',
      'sap_skills_bundle',
      'sap_skills_install',
      'sap_skills_upgrade_plan',
      'sap_runtime_repair_plan',
      'sap_skills_check_updates',
      'sap_skills_self_update',
    ],
    register: registerSkillsTools,
  }),
  createToolModule({
    id: 'magicblock',
    title: 'MagicBlock',
    description: 'MagicBlock ER Router, private payment, and VRF tool family.',
    category: 'integration',
    order: 270,
    expectedTools: [
      'magicblock_health',
      'magicblock_balance',
      'magicblock_private_balance',
      'magicblock_transfer',
      'magicblock_swap',
      'magicblock_swap_quote',
    ],
    register: registerMagicBlockTools,
  }),
  createToolModule({
    id: 'memory',
    title: 'Local Memory',
    description: 'Local memory, strategies, streams, audit, and agent learning tools.',
    category: 'memory',
    order: 280,
    expectedTools: [
      'sap_memory_record',
      'sap_memory_search',
      'sap_memory_summarize',
      'sap_memory_recall',
      'sap_memory_prune',
      'sap_strategy_save',
      'sap_strategy_load',
      'sap_strategy_list',
      'sap_strategy_activate',
      'sap_stream_buffer',
      'sap_stream_consume',
      'sap_stream_replay',
      'sap_audit_query',
      'sap_audit_record',
      'sap_audit_stats',
      'sap_hermes_search',
      'sap_hermes_recent',
      'sap_strategy_execute',
      'sap_trade_journal',
      'sap_trade_journal_query',
    ],
    register: registerMemoryTools,
  }),
] as const;

export function resolveBuiltinToolModulesForContext(context: SapMcpContext): readonly ToolModuleDefinition[] {
  return selectToolModulesForContext(BUILTIN_TOOL_MODULES, context);
}
