/**
 * @module memory/memory-store
 * @description Store for agent memories — LLM-compressed summaries of past interactions.
 *
 * Memories are created by the agent (or auto-generated by the summarize tool)
 * and stored with a relevance score that decays over time. The FTS5 index
 * enables semantic search across all memories for context injection.
 */

import { memoryDatabase } from './database.js';
import { decayRelevance, isExpired } from './utils.js';
import type { AgentMemoryRecord, MemoryType, MemorySearchResult, MemoryQueryOptions } from './types.js';

/**
 * @name MemoryStore
 * @description Manages agent memory records with relevance decay and FTS5 search.
 */
export class MemoryStore {
  /**
   * @name record
   * @description Creates a new agent memory entry.
   * @param record - Memory data to record (without id, timestamps, relevance).
   * @param initialRelevance - Initial relevance score 0-1. Default 0.8.
   * @returns The inserted record ID, or -1 if degraded.
   */
  record(
    record: Pick<AgentMemoryRecord, 'memoryType' | 'category' | 'summary' | 'sourceToolCalls' | 'expiresAt'>,
    initialRelevance = 0.8,
  ): number {
    if (memoryDatabase.isDegraded()) return -1;
    memoryDatabase.init();

    const stmt = memoryDatabase.getStatement('insert_memory');
    if (!stmt) return -1;

    const result = stmt.run({
      memoryType: record.memoryType,
      category: record.category,
      summary: record.summary,
      sourceToolCalls: record.sourceToolCalls ?? null,
      relevanceScore: Math.max(0, Math.min(1, initialRelevance)),
      expiresAt: record.expiresAt ?? null,
    });

    return result.lastInsertRowid as number;
  }

  /**
   * @name search
   * @description Full-text search across agent memories using FTS5.
   * Results are ranked by BM25 relevance with decayed score.
   */
  search(options: MemoryQueryOptions): MemorySearchResult<AgentMemoryRecord & { decayedRelevance: number }> {
    if (memoryDatabase.isDegraded()) {
      return { results: [], total: 0, hasMore: false };
    }
    memoryDatabase.init();

    const db = memoryDatabase.getDb();
    const limit = Math.min(options.limit ?? 20, 100);
    const offset = options.offset ?? 0;

    let whereClause = '';
    const params: Record<string, unknown> = { limit, offset };

    if (options.memoryType) {
      whereClause += ' AND m.memory_type = @memoryType';
      params['memoryType'] = options.memoryType;
    }
    if (options.category) {
      whereClause += ' AND m.category = @category';
      params['category'] = options.category;
    }

    const ftsQuery = this.buildFtsQuery(options.query);

    const sql = `
      SELECT m.id, m.memory_type, m.category, m.summary, m.source_tool_calls,
             m.relevance_score, m.created_at, m.expires_at, m.last_accessed_at
      FROM agent_memory_fts fts
      JOIN agent_memory m ON m.id = fts.rowid
      WHERE agent_memory_fts MATCH @ftsQuery
      ${whereClause}
      ORDER BY ${options.sort === 'newest' ? 'm.created_at DESC' : options.sort === 'oldest' ? 'm.created_at ASC' : 'bm25(agent_memory_fts)'}
      LIMIT @limit OFFSET @offset
    `;

    params['ftsQuery'] = ftsQuery;

    try {
      const rows = db.prepare(sql).all(params) as AgentMemoryRecord[];
      const results = rows.map(row => ({
        ...row,
        decayedRelevance: decayRelevance(row.relevanceScore, row.createdAt, 0.01),
      }));

      // Filter by minimum relevance (after decay).
      const filtered = options.minRelevance
        ? results.filter(r => r.decayedRelevance >= (options.minRelevance ?? 0))
        : results;

      // Filter out expired memories.
      const active = filtered.filter(r => !isExpired(r.expiresAt));

      // Update last_accessed_at for returned memories.
      const updateStmt = memoryDatabase.getStatement('update_memory_access');
      if (updateStmt) {
        for (const r of active) {
          if (r.id) updateStmt.run(r.id);
        }
      }

      return {
        results: active,
        total: active.length,
        hasMore: false,
      };
    } catch {
      return { results: [], total: 0, hasMore: false };
    }
  }

  /**
   * @name recall
   * @description Returns the most relevant memories for a given category.
   * Used for prompt injection — the agent gets the top N memories ordered
   * by decayed relevance.
   * @param category - Tool category to recall memories for.
   * @param limit - Maximum number of memories. Default 5.
   * @returns Relevant memories sorted by decayed relevance.
   */
  recall(category: string, limit = 5): AgentMemoryRecord[] {
    if (memoryDatabase.isDegraded()) return [];
    memoryDatabase.init();

    const db = memoryDatabase.getDb();
    try {
      const rows = db.prepare(
        `SELECT * FROM agent_memory
         WHERE category = ? AND (expires_at IS NULL OR expires_at > datetime('now'))
         ORDER BY relevance_score DESC
         LIMIT ?`
      ).all(category, limit) as AgentMemoryRecord[];

      // Update last_accessed_at.
      const updateStmt = memoryDatabase.getStatement('update_memory_access');
      if (updateStmt) {
        for (const row of rows) {
          if (row.id) updateStmt.run(row.id);
        }
      }

      return rows;
    } catch {
      return [];
    }
  }

  /**
   * @name count
   * @description Returns the total number of agent memory records.
   */
  count(): number {
    if (memoryDatabase.isDegraded()) return 0;
    memoryDatabase.init();
    const stmt = memoryDatabase.getStatement('count_memory');
    if (!stmt) return 0;
    return (stmt.get() as { count: number }).count;
  }

  /**
   * @name memoryTypeBreakdown
   * @description Returns counts grouped by memory type.
   */
  memoryTypeBreakdown(): Record<MemoryType, number> {
    if (memoryDatabase.isDegraded()) {
      return { lesson: 0, pattern: 0, failure: 0, success: 0 };
    }
    memoryDatabase.init();
    const stmt = memoryDatabase.getStatement('count_memory_by_type');
    if (!stmt) return { lesson: 0, pattern: 0, failure: 0, success: 0 };

    const rows = stmt.all() as Array<{ memory_type: MemoryType; count: number }>;
    const result: Record<MemoryType, number> = { lesson: 0, pattern: 0, failure: 0, success: 0 };
    for (const row of rows) {
      result[row.memory_type] = row.count;
    }
    return result;
  }

  /**
   * @name lastMemoryAt
   * @description Returns the timestamp of the most recent memory.
   */
  lastMemoryAt(): string | null {
    if (memoryDatabase.isDegraded()) return null;
    memoryDatabase.init();
    const stmt = memoryDatabase.getStatement('last_memory_at');
    if (!stmt) return null;
    const row = stmt.get() as { created_at: string } | undefined;
    return row?.created_at ?? null;
  }

  /**
   * @name prune
   * @description Removes expired memories and memories with relevance below
   * the threshold after decay.
   * @param minRelevance - Minimum decayed relevance to keep. Default 0.05.
   * @returns Number of memories pruned.
   */
  prune(minRelevance = 0.05): number {
    if (memoryDatabase.isDegraded()) return 0;
    memoryDatabase.init();
    const db = memoryDatabase.getDb();

    // Delete expired memories.
    const expiredResult = db.prepare(
      `DELETE FROM agent_memory WHERE expires_at IS NOT NULL AND expires_at <= datetime('now')`
    ).run();

    // Delete low-relevance memories (check decayed relevance in JS to avoid
    // complex SQL — better-sqlite3 is synchronous so this is fast).
    const allRows = db.prepare(
      `SELECT id, relevance_score, created_at FROM agent_memory`
    ).all() as Array<{ id: number; relevance_score: number; created_at: string }>;

    let pruned = expiredResult.changes;
    for (const row of allRows) {
      const decayed = decayRelevance(row.relevance_score, row.created_at, 0.01);
      if (decayed < minRelevance) {
        db.prepare('DELETE FROM agent_memory WHERE id = ?').run(row.id);
        pruned++;
      }
    }

    return pruned;
  }

  /**
   * @name buildFtsQuery
   * @description Converts a natural language query into a FTS5 MATCH expression.
   * @internal
   */
  private buildFtsQuery(query: string): string {
    const escaped = query.replace(/["'*:]/g, ' ').trim();
    if (!escaped) return '*';
    const words = escaped.split(/\s+/).filter(w => w.length > 0);
    if (words.length === 1) return `"${words[0]}"*`;
    return words.map(w => `"${w}"*`).join(' OR ');
  }
}

/**
 * @name memoryStore
 * @description Singleton instance of the memory store.
 */
export const memoryStore = new MemoryStore();